name: rainboot

services:
  frontend:
    container_name: rainboot_frontend
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:4000
    volumes:
      # - ../apps/frontend:/app/apps/frontend
      - /app/node_modules
      - /app/apps/frontend/node_modules
    depends_on:
      - backend

  backend:
    container_name: rainboot_backend
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/backend.Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - REDIS_URL=redis://redis:6379
    volumes:
      # - ../apps/backend:/app/apps/backend
      - /app/node_modules
      - /app/apps/backend/node_modules
    depends_on:
      - redis

  redis:
    container_name: rainboot_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
